local objects = {
  {
    id = 1,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 100,
    y = 250,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 2,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 120,
    y = 220,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 3,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 150,
    y = 210,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 4,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 265,
    y = 180,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 54,
    visible = true,
    properties = {}
  },
  {
    id = 5,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 300,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 6,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 370,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 7,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 390,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },
  {
    id = 8,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 430,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },    
  {
    id = 9,
    name = "Coin",
    type = "",
    shape = "rectangle",
    x = 450,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 49,
    visible = true,
    properties = {}
  },   
  {
    id = 10,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 175,
    y = 230,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 54,
    visible = true,
    properties = {}
  },
  {
    id = 11,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 410,
    y = 160,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 54,
    visible = true,
    properties = {}
  },
  {
    id = 12,
    name = "Gem",
    type = "",
    shape = "rectangle",
    x = 768,
    y = 250,
    width = 16,
    height = 16,
    rotation = 0,
    gid = 54,
    visible = true,
    properties = {}
  }
}


return objects
